/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiverRouteRouteImport } from './routes/waiver/route'
import { Route as TrendingRouteRouteImport } from './routes/trending/route'
import { Route as TestRouteRouteImport } from './routes/test/route'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AnalysisRouteRouteImport } from './routes/analysis/route'

const WaiverRouteRoute = WaiverRouteRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRouteRoute = TrendingRouteRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRouteRoute = AnalysisRouteRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/analysis': typeof AnalysisRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/test': typeof TestRouteRoute
  '/trending': typeof TrendingRouteRoute
  '/waiver': typeof WaiverRouteRoute
}
export interface FileRoutesByTo {
  '/analysis': typeof AnalysisRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/test': typeof TestRouteRoute
  '/trending': typeof TrendingRouteRoute
  '/waiver': typeof WaiverRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/analysis': typeof AnalysisRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/login': typeof LoginRouteRoute
  '/signup': typeof SignupRouteRoute
  '/test': typeof TestRouteRoute
  '/trending': typeof TrendingRouteRoute
  '/waiver': typeof WaiverRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/analysis'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/test'
    | '/trending'
    | '/waiver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analysis'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/test'
    | '/trending'
    | '/waiver'
  id:
    | '__root__'
    | '/analysis'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/test'
    | '/trending'
    | '/waiver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnalysisRouteRoute: typeof AnalysisRouteRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  SignupRouteRoute: typeof SignupRouteRoute
  TestRouteRoute: typeof TestRouteRoute
  TrendingRouteRoute: typeof TrendingRouteRoute
  WaiverRouteRoute: typeof WaiverRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AnalysisRouteRoute: AnalysisRouteRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  SignupRouteRoute: SignupRouteRoute,
  TestRouteRoute: TestRouteRoute,
  TrendingRouteRoute: TrendingRouteRoute,
  WaiverRouteRoute: WaiverRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
