version: "3.9"

services:
    frontend:
        build: ./frontend
        ports:
            - "80:80"
        depends_on:
            - backend
        restart: unless-stopped

    backend:
        build: ./backend
        ports:
            - "3300:3300"
        restart: unless-stopped
